site_name: ytimyno
site_url: https://ytimyno.github.io/
site_description: Research hub.
site_author: ytimyno

# Repository
repo_name: ytimyno.github.io
repo_url: https://github.com/ytimyno/ytimyno.github.io

theme:
  name: material
  logo: images/patriciar_crop.png
dev_addr: 0.0.0.0:8080

nav:
  - Home : index.md
  - CI/CD :
    - Resources & Pipelines : blog/cicd/protected_resources.md
    - Resource Lifecycle : blog/cicd/access_lifecycle.md
    - Execution Agents : blog/cicd/execution_agents.md
  - Playground :
    - Supply Chain x Build Agents : blog/technical/cicd/exec_agents.md
    - Weaponizing Open Source : blog/technical/py_git_revshell.md
    - PaC on Metadata : blog/technical/pac/pac_on_rails.md

# Example in https://github.com/Nethereum/Nethereum.Docs
# python -m mkdocs gh-deploy --remote-branch main